### ISSUE TITLE
Expand autocomplete to input size

### ISSUE THREAD

**Issue by josegonzalez** [seatgeek/hell#10]
This isn't good, especially on mobile:

![http://cl.ly/image/3q3l2v2z2E0C](http://f.cl.ly/items/0T1A2O3a290p0z0R0k0h/Screen%20Shot%202013-03-04%20at%202.06.30%20AM.png)

**Comment by josegonzalez** [comment]
https://github.com/twitter/bootstrap/issues/1653 seems to say this isn't possible, given that the input width changes on browser resize. Might make sense to replace with something that is aware of the input width, or add some sort of callback to the bootstrap tooltip js to expand the width based on input width.

**Comment by bytedevzone** [comment]
Open jquery-typeahead.js and find out the function 'show' and modify as given below. 
it will work
 //------------------------------------------------------------------
        //
        //  Shows the results list
        //
        show: function () {
            var pos = $.extend({}, this.$element.offset(), {
                height: this.$element[0].offsetHeight,
                width: this.$element[0].offsetWidth
            });

```
        this.$menu.css({
            top: pos.top + pos.height,
            left: pos.left,
            width: pos.width
        });

        this.$menu.show();
        this.shown = true;

        return this;
    },
```
